name: My First Robot

on: push

jobs:
  check-code:
    runs-on: ubuntu-latest
    steps:
      - name: Get my code
        uses: actions/checkout@v4

      - name: Run my app
        run: python3 app.py

      - name: Build Docker image
        run: docker build -t my-app .
